# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{assertor}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Enrique García Cota"]
  s.date = %q{2011-05-24}
  s.description = %q{Very minimal unit test lib for ruby.}
  s.email = %q{kikito@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "assertor.gemspec",
    "lib/assertor.rb",
    "lib/assertor/assert_failed_exception.rb",
    "lib/assertor/case.rb",
    "lib/assertor/reporter.rb",
    "run_tests.rb",
    "test/case_tests/assertions/assert_equals_test.rb",
    "test/case_tests/assertions/assert_not_test.rb",
    "test/case_tests/assertions/assert_raises_test.rb",
    "test/case_tests/assertions/assert_test.rb",
    "test/case_tests/class_methods/all_test.rb",
    "test/case_tests/class_methods/ignore_test.rb",
    "test/case_tests/class_methods/run_all_test.rb",
    "test/case_tests/class_methods/run_test.rb",
    "test/case_tests/class_methods/tests_test.rb",
    "test/helper.rb",
    "test/reporter_tests/defaults_test.rb",
    "test/reporter_tests/run_test.rb"
  ]
  s.homepage = %q{http://github.com/kikito/assertor}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Very minimal unit test lib for ruby.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

